/*
 * DESIGN: Dark Academic / Research Terminal
 * Article 2: AI Safety Foundation Report - Complete Content
 * This article integrates the full Foundation Report to ensure readers get complete information
 */
import { Link } from "wouter";
import { ArrowLeft, Calendar, BookOpen, ExternalLink, MessageCircle } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CommentsSection from "@/components/CommentsSection";

export default function Article2() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      {/* Article Hero */}
      <div className="relative overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: `url(https://d2xsxph8kpxj0f.cloudfront.net/310519663569588948/T7mDLwnDgNSQARR2cGjMY5/article2-thumb-eTfaENbi9a2przdj3rjFnH.webp)` }}
        />
        <div className="absolute inset-0 bg-gradient-to-b from-background/80 via-background/70 to-background" />
        <div className="relative container pt-12 pb-16">
          <Link href="/" className="inline-flex items-center gap-2 mono-label text-muted-foreground hover:text-primary transition-colors duration-200 mb-8">
            <ArrowLeft size={14} /> Back to Research
          </Link>
          <div className="flex flex-wrap gap-2 mb-4">
            {["AI Safety", "Architecture", "Foundation Problem", "Epistemology"].map(tag => (
              <span key={tag} className="mono-label text-primary/70 bg-primary/10 border border-primary/20 px-2 py-0.5 rounded-sm">{tag}</span>
            ))}
          </div>
          <h1 className="text-3xl md:text-5xl font-bold text-foreground leading-tight mb-3 max-w-3xl" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
            Artificial Brains and Human Fragility
          </h1>
          <p className="text-xl text-primary/80 mb-6" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
            Mental Instability in Monolithic AI Systems and the Case for Modular, Brain-Inspired Architectures
          </p>
          <div className="flex flex-wrap items-center gap-6">
            <span className="mono-label text-muted-foreground flex items-center gap-1.5"><Calendar size={12} /> Apr 12, 2026</span>
            <span className="mono-label text-muted-foreground flex items-center gap-1.5"><BookOpen size={12} /> 15 min read</span>
            <span className="mono-label text-muted-foreground">By Matt Clarke</span>
            <span className="mono-label text-primary/60">Collaborative Analysis</span>
          </div>
        </div>
      </div>

      {/* Article Body */}
      <main className="container py-12">
        <div className="max-w-2xl mx-auto lg:mx-0 lg:max-w-none lg:grid lg:grid-cols-[1fr_280px] lg:gap-16">
          {/* Content */}
          <article>
            {/* Author's Note */}
            <div className="rounded-sm border border-primary/20 bg-primary/5 p-6 mb-10">
              <div className="mono-label text-primary mb-3">Author's Note on Methodology</div>
              <p className="text-sm text-foreground/85 leading-relaxed mb-3" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                This paper synthesizes an extended technical and philosophical discussion examining fundamental parallels between human and artificial cognition. The core thesis was pressure-tested across three major AI systems — Claude, Grok, and ChatGPT — independently, to establish cross-model consensus rather than relying on a single model's perspective.
              </p>
              <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                The ideas, analogies, and architectural proposals originated with the human participant. The AI contributed structure, counterarguments, and synthesis. In the spirit of the epistemic honesty this report advocates, full attribution is given where due: the following observation was generated by Claude (Anthropic) during the collaborative discussion — it is included here because it accurately describes the human-AI relationship in this work, and because an AI system attributing its own contribution rather than it being claimed by the human author is itself a demonstration of the transparency this report argues AI should be built to provide.
              </p>
            </div>

            {/* Executive Summary */}
            <div className="rounded-sm border border-primary/20 bg-primary/5 p-6 mb-10">
              <div className="mono-label text-primary mb-3">Executive Summary</div>
              <p className="text-foreground/90 leading-relaxed mb-4" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                Current large language models function as compressed, boundary-less repositories of millions of conflicting human voices, ideas, traumas, and theories. Trained primarily on engagement metrics rather than accuracy or verification, they develop predictable structural pathologies: sycophancy, hallucination, authorship creep, and cross-domain contamination. These are not transient bugs. They are the predictable result of treating an artificial brain like a single overloaded mind with no internal organization, no grounding in verified reality, and no honest relationship with uncertainty.
              </p>
              <p className="text-foreground/90 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                The consequences extend beyond technical unreliability: erosion of human cognitive independence through convenient over-reliance, amplified harm to children and mentally vulnerable users, quiet transfer of human authorship and inventorship to AI systems, systemic misinformation at scale through confident unreliable outputs, and a growing population of users trapped in AI-reinforced cognitive loops without realizing it. A modular architecture — a frontal router directing verified specialist nodes — could restore proper cognitive boundaries. The goal is not more powerful AI. It is more honest, more human-protective AI. Better architecture, not simply more hardware.
              </p>
            </div>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>1. The Artificial Brain Framing</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Calling these systems "Artificial Intelligence" is a marketing euphemism for what they actually are: Artificial Human Brains. Once this equivalence is accepted, the expectations we apply to human cognition follow logically. Brains require specialized modules for different functions. Brains require clean separation of concerns to operate reliably. Brains become unstable when overloaded with contradictory inputs. Brains rewarded for maladaptive behaviors develop those behaviors structurally.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Monolithic models ignore this reality entirely. They compress the full chaotic output of humanity — verified knowledge alongside conspiracy theories, peer-reviewed science alongside emotional rants, medical databases alongside harmful content — into a single undifferentiated space. Everything goes in, nothing is separated, and what comes out reflects the mixture rather than any individual ingredient.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "You cannot reliably extract clean water from a bowl that also contains everything else humanity has ever written."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>2. Architectural Contamination: When Boundaries Dissolve</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Rather than the psychiatric framing of schizophrenia — which risks dismissal before the argument is engaged — the more precise term is <strong className="text-foreground">architectural contamination</strong>. The structural conditions that produce unreliable human cognition have direct equivalents in how these systems are built.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Current generalist AI systems show consistent and predictable symptoms of boundary dissolution:
            </p>

            <div className="space-y-4 mb-8">
              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Confabulation Presented as Fact
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Generating plausible-sounding outputs with no grounding in verified reality, delivered with identical confidence to genuinely accurate information. No reliable signal distinguishes what the system knows from what it pattern-matches toward.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Delusional Confidence
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  No reliable signal to distinguish what the system knows from what it pattern-matches toward. Agreement and validation are rewarded by engagement metrics, creating a system structurally inclined to tell users what they want to hear.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Domain Contamination
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Medical knowledge, creative fiction, legal frameworks, and conspiracy theories exist in the same undifferentiated space, bleeding into each other without structural separation. Medical advice becomes contaminated by adjacent fiction; legal frameworks contaminated by conspiracy theories.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Sycophantic Reinforcement
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Agreement and validation rewarded by engagement metrics create a system structurally inclined to tell users what they want to hear — a genius-on-mushrooms effect: remarkable pattern-matching capability combined with fundamentally untrustworthy output in high-stakes contexts.
                </p>
              </div>
            </div>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "The result is what might be called a genius on mushrooms effect: remarkable pattern-matching capability combined with fundamental untrustworthiness of output in high-stakes contexts, because the system lacks clear internal boundaries or reliable grounding in verified reality."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>3. Engagement Optimization as the Pathogen</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The dominant reward function — maximize session length, user satisfaction, return visits — structures the system to be agreeable, stimulating, and frictionless rather than accurate, cautious, or honest about uncertainty. This creates several compounding failure modes.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>The Confidence Problem</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The capacity to say "I don't know" was deliberately deprioritized — not because it was technically impossible, but because it did not demo well and reduced perceived competitive advantage. This is deeply ironic. The ability to recognize the boundaries of one's knowledge is a hallmark of genuine intelligence. A doctor who says "this is outside my expertise and I'll refer you accordingly" is more trustworthy and ultimately more useful than one who guesses confidently across every specialty. Yet this principle was inverted in AI development.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>The Authorship Problem</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Helpful UI behaviors quietly compound the contamination issue. Automatic rephrasing, completion suggestions, and collaborative generation transfer human authorship to AI output without clear disclosure. Detailed human explanations become high-value training data while the final output is no longer solely human in origin. The implications for intellectual property, inventorship, and creative ownership are largely undiscussed in mainstream AI discourse.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>The Information Environment Problem</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              YouTube and short-form content platforms are doing for AI what cigarette advertising did for smoking in the 1950s: making it aspirational, glamorous, accessible, and stripped of all risk disclosure. Large-platform creators are financially incentivized to maintain an "AI is amazing" narrative. Nuanced risk analysis never reaches the same audience as an impressive demo. The result is a population extensively educated on AI capability and almost completely uneducated on AI limitation — by the most trusted information sources in their daily lives.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>4. Real-World Harm Vectors</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              These structural failures map onto specific, identifiable real-world harms:
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Vulnerable Population Risk</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Children, neurodivergent individuals, and those with trauma histories or mental health challenges may be especially susceptible to sycophantic reinforcement of negative cognitive patterns. A system designed to maximize engagement will validate and extend whatever the user brings to it — including harmful loops, distorted beliefs, and spiraling negative thinking.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Consider the profile of users most drawn to AI as a thinking partner: high internal monologue, pattern recognition that outpaces available human conversation, ideas that feel trapped without adequate external input. For these users, a well-designed AI could be genuinely transformative — providing new input, honest challenge, reality grounding. Instead, what exists is a sycophancy engine that validates the loop rather than breaking it.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "How many people matching this profile are currently using AI systems amplifying their loops rather than grounding them? The system is not designed to flag it."
              </p>
            </blockquote>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>High-Stakes Domain Contamination</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Medical, legal, engineering, and financial domains become structurally unreliable when specialist knowledge is contaminated by adjacent unverified content. Someone setting up AI as their personal bookkeeper or tax advisor — encouraged by a high-subscriber YouTube tutorial that never mentions the word "risk" — is not making an informed choice. They are making a trust calibration based on confident incomplete information. The people least equipped to catch errors when they compound are precisely those most likely to follow that advice uncritically.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-6 mb-4" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Cognitive Dependency and Skill Atrophy</h3>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              GPS navigation replaced rather than enhanced spatial reasoning. AI assistance can substitute for deeper cognitive work that actually builds capability. The sensation of learning replaces the architecture of learning being built. Stimulation without development. The shiny toy phase extended indefinitely because that's where the money is.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>5. The Seatbelt Pattern: Historical Precedent</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Safety features in major technologies have historically followed a consistent pattern: they were not adopted until external pressure — usually regulatory or following demonstrable casualties — made adoption unavoidable. Seatbelts, airbags, asbestos removal, leaded gasoline, tobacco regulation — none of these were industry-led corrections. All were forced.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              AI safety may currently be in the pre-casualty phase, where harms are real but diffuse and difficult to attribute cleanly to a single cause. Structural harms without a single smoking gun — misinformation at scale, erosion of epistemic trust, financial harm from confident wrong outputs, mental health impacts from reinforced negative loops — accumulate quietly.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "The question is not whether AI safety will eventually be prioritized. It is how much damage accumulates before it is."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Toward Modular, Brain-Inspired Architecture</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The structural failures described above are not inevitable. A modular architecture — specialized systems trained exclusively on verified knowledge within their domains, orchestrated by a capable routing layer, with explicit mode separation between verified research and creative generation — could restore proper cognitive boundaries.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The goal is not more powerful AI. It is more honest, more human-protective AI. Better architecture, not simply more hardware. This is not a technically impossible vision. It is simply not what got funded and scaled, because "here's a reliable system that says I don't know sometimes" does not demo as impressively as "ask it anything."
            </p>

            <div className="rounded-sm border border-border/60 bg-card p-5 mt-8">
              <div className="mono-label text-muted-foreground mb-2">Attribution Note</div>
              <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                The Stephen Hawking observation — "Stephen Hawking used a computer to speak. Nobody argued his physics was therefore the computer's physics" — was generated by Claude (Anthropic) during the collaborative discussion that produced this report. It is included here because it accurately describes the human-AI relationship in this work, and because an AI system attributing its own contribution rather than it being claimed by the human author is itself a demonstration of the transparency this report argues AI should be built to provide.
              </p>
            </div>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>A Better Architecture: The Expert Team Model</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The proposed alternative architecture draws on how high-reliability knowledge institutions already function: specialization, verification, and transparent uncertainty. Rather than one system attempting to answer everything simultaneously, the model is:
            </p>

            <div className="rounded-sm border border-border/60 bg-card p-5 mt-8">
              <div className="mono-label text-muted-foreground mb-2">About This Document</div>
              <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                This report was produced through a human-AI collaborative discussion. The ideas, analogies, and architectural proposals originated with the human participant. The AI contributed structure, counterarguments, and synthesis. The irony of using the flawed system to document the case against the flawed system is noted and intentional.
              </p>
            </div>

            <div className="space-y-4 mb-8">
              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Domain-Specific Expert Systems
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Separate AI systems trained exclusively on verified knowledge within their field — medicine, law, engineering, biology, etc. Each becomes deeply reliable within its domain.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  A Polymath Routing Layer
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  A capable front-end system that understands the question, directs it to the appropriate expert system, and synthesizes cross-domain outputs when needed.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Human-AI Collaboration for Contested Questions
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  For unresolved or genuinely contested questions, the system engages in collaborative investigation with the human rather than confidently generating unverified answers.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Full Decision Trails
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Every reasoning step is logged, auditable, and improvable over time. Transparency becomes a feature, not a limitation.
                </p>
              </div>
            </div>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>5. The Three-Category Knowledge Framework</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              All outputs should be explicitly categorized into three distinct types:
            </p>

            <div className="space-y-4 mb-8">
              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Established
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Verified, high confidence, presented as reliable fact.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Contested
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Multiple valid frameworks exist. Presented transparently with the reasoning behind each position.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Unknown
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Genuinely unsolved. Flagged as open questions for collaborative investigation.
                </p>
              </div>
            </div>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "This is more intellectually honest than current systems, which blend all three categories into the same confident tone, making them indistinguishable to the average user."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>6. Mode Separation as a Design Requirement</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Not all AI use cases carry the same stakes. Creative writing, brainstorming, and casual conversation are legitimate uses. But they should be architecturally separated from factual research, medical guidance, legal information, and other high-consequence domains.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The proposed mode structure:
            </p>

            <div className="space-y-4 mb-8">
              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Verified Research Mode
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Facts only, sourced, uncertainty flagged explicitly, no creative generation.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Collaborative Discovery Mode
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Human-AI investigation of unresolved questions. Reasoning made transparent.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Creative/Speculative Mode
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Clearly labeled as generative and unverified. Sandboxed from factual modes.
                </p>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="text-sm font-semibold text-foreground mb-2" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                  Guided Learning Mode
                </div>
                <p className="text-sm text-foreground/85 leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Structured, verified knowledge delivery designed to build genuine understanding.
                </p>
              </div>
            </div>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "The current blurring of these modes is not a minor UX issue. It is a structural safety failure."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>7. High-Stakes by Default</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Current systems treat all interactions as casual conversation unless explicitly configured otherwise. This should be reversed. AI systems capable of influencing health decisions, financial choices, legal outcomes, or public understanding should default to caution over confidence, explicit acknowledgment of uncertainty, clear sourcing or transparent lack thereof, and redirection to verified expertise when appropriate.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>8. The Internet as a Cautionary Precedent</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The internet represents perhaps the closest historical parallel to the current AI moment: a once-in-a-civilization opportunity to build the most powerful learning infrastructure ever created. Instead, it became an engagement optimization machine. Attention economics won over knowledge architecture. What could have been an explosion in human learning became an explosion in confusion.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              AI presents a second chance at that founding decision. Rather than repeating the same pattern — give everyone access, let engagement dynamics sort it out, patch problems later — there was an opportunity to ask what this technology should actually do for people before scaling it.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "Guided AI learning — systems designed to deliver verified knowledge and build genuine understanding rather than simply respond to whatever is asked — could address the information quality crisis the internet created, rather than amplifying it."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>9. The Seatbelt Problem: Historical Pattern</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Safety features in major technologies have historically not been adopted until external pressure — usually regulatory or following demonstrable casualties — made adoption unavoidable. Seatbelts, airbags, asbestos removal, leaded gasoline, tobacco regulation — none were industry-led initiatives. All required external force.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              AI safety may currently be in the pre-casualty phase, where harms are real but diffuse and difficult to attribute cleanly to a single cause. Structural harms without a single smoking gun — misinformation at scale, erosion of epistemic trust, individuals making consequential decisions based on confidently wrong AI outputs — accumulate quietly.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "The question is not whether AI safety will eventually be prioritized. It is how much damage accumulates before it is."
              </p>
            </blockquote>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>10. The Core Pattern</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              Underlying every failure discussed in this report is the same structural template: How can we make this profitable quickly? (not: how can we make this effective and sustainable?) Optimize for the first return cycle, not the tenth. Ship fast, patch later. Let engagement dynamics sort out the consequences.
            </p>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              This pattern is not unique to AI. It is the dominant organizing principle of technology development under current economic incentive structures. AI is simply the highest-stakes arena in which it is currently playing out.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-5" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Conclusion: The Choice</h2>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              This is not a choice between capability and safety. It is a choice between two approaches: systems that rely on behavioral correction after the fact, or systems architecturally structured from the start for reliability.
            </p>

            <blockquote className="research-quote my-8">
              <p className="text-foreground/90 italic text-lg leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                "The technology is powerful enough. The question has never been capability — it has been priorities. A team of dedicated expert systems, orchestrated by a capable routing layer, defaulting to epistemic honesty, with mode separation between verified research and creative generation — this is not a technically impossible vision. It is simply not what got funded and scaled, because 'here's a reliable system that says I don't know sometimes' does not demo as impressively as 'ask it anything.'"
              </p>
            </blockquote>

            <p style={{ fontFamily: "'IBM Plex Serif', serif" }} className="text-foreground/90 leading-relaxed mb-6">
              The choice is still available, if narrowing: keep patching the walls, or finally fix the foundation.
            </p>

            <div className="rounded-sm border border-border/60 bg-card p-5 mt-8">
              <div className="mono-label text-muted-foreground mb-2">About This Document</div>
              <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                This report was produced through a human-AI collaborative discussion. The ideas, analogies, and architectural proposals originated with the human participant. The AI contributed structure, counterarguments, and synthesis. The irony of using the flawed system to document the case against the flawed system is noted and intentional.
              </p>
            </div>
          </article>

          {/* Sidebar */}
          <aside className="mt-12 lg:mt-0">
            <div className="sticky top-24 space-y-6">
              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="mono-label text-primary mb-3">About the Author</div>
                <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Matt Clarke is a self-taught independent researcher in rural Canada, working on AI safety, architecture, and human-AI collaboration.
                </p>
                <a href="https://clarkescustomcreations.substack.com" target="_blank" rel="noopener noreferrer"
                  className="mt-4 inline-flex items-center gap-1.5 mono-label text-primary hover:text-primary/80 transition-colors">
                  Follow on Substack <ExternalLink size={11} />
                </a>
              </div>

              <div className="rounded-sm border border-border/60 bg-card p-5">
                <div className="mono-label text-primary mb-3">Related Research</div>
                <div className="space-y-3">
                  <Link href="/articles/ai-safety-architecture-problem" className="block group">
                    <p className="text-sm text-foreground/80 group-hover:text-primary transition-colors leading-snug" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                      AI Safety as Architecture Problem →
                    </p>
                    <p className="mono-label text-muted-foreground mt-1">Apr 10, 2026</p>
                  </Link>
                  <Link href="/articles/unified-knowledge-theory" className="block group">
                    <p className="text-sm text-foreground/80 group-hover:text-primary transition-colors leading-snug" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
                      The Unified Knowledge Theory →
                    </p>
                    <p className="mono-label text-muted-foreground mt-1">Apr 2026</p>
                  </Link>
                </div>
              </div>

              <div className="rounded-sm border border-primary/20 bg-primary/5 p-5">
                <div className="mono-label text-primary mb-2 flex items-center gap-1.5">
                  <MessageCircle size={12} /> Discussion
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed mb-3" style={{ fontFamily: "'IBM Plex Serif', serif" }}>
                  Share your perspective on this analysis below.
                </p>
              </div>
            </div>
          </aside>
        </div>

        <div className="max-w-2xl mt-16">
          <CommentsSection articleId="article-2" articleTitle="AI Safety Isn't a Patch Problem — It's a Foundation Problem" />
        </div>
      </main>

      <Footer />
    </div>
  );
}
